dist: xenial
sudo: required
before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.37.1_Linux-64bit.deb
script:
  - hugo
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    repo: simonmika/simonmika.com
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
