baseURL: "https://simonmika.com/"
languageCode: "en-us"
title: "Simon says"
theme: "hugo-theme-html5"
metaDataFormat: "yaml"
paginate: 100
disqusShortname: "simonmika"
googleAnalytics: "UA-83177710-2"

params:
  description: "truths, opinions and preconceptions"
  logotype: "img/logotype.svg"
  css:
    - "css/text.css"
    - "css/color.css"
    - "css/layout.css"
    - "css/form.css"
    - "css/blockquotes.css"
  listMode: "header"
  frontPageMode: "header"
  frontPageSection: "article"
  navigationInHeader: true
  prefix:
    - "og: http://opy.me/ns#"

menu:
  main:
    - name: "Articles"
      weight: 10
      url: "/"
    - name: "Talks"
      weight: 20
      url: "/talk"
