baseURL: "./"
languageCode: "en-us"
title: "Simon says"
theme: "hugo-theme-html5"

# Modern Hugo Features
enableGitInfo: true
enableRobotsTXT: true
enableEmoji: true

# Content Management
buildDrafts: false
buildFuture: false
buildExpired: false

# Markdown Processor Configuration
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

# Pagination
pagination:
  path: "page"
  pagerSize: 100

# Output Formats & URLs
permalinks:
  posts: /:year/:month/:title/

# Site Parameters
params:
  description: "truths, opinions and preconceptions"
  logotype: "img/logotype.svg"
  css:
    - "css/text.css"
    - "css/color.css"
    - "css/layout.css"
    - "css/form.css"
    - "css/blockquotes.css"
  listMode: "header"
  frontPageMode: "header"
  frontPageSection: "article"
  navigationInHeader: true
  prefix:
    - "og: http://opy.me/ns#"

# Menu Configuration
menu:
  main:
    - name: "Articles"
      weight: 10
      url: "/"
    - name: "Talks"
      weight: 20
      url: "/talk"
