/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { binotype } from "@binotype/model";
export { binotype } from "@binotype/model";
export namespace Components {
    interface BinotypeSite {
        /**
          * @default false
         */
        "debug": boolean | "site" | "context";
        "site"?: binotype.Site | string;
    }
    interface SampleSite {
    }
}
declare global {
    interface HTMLBinotypeSiteElement extends Components.BinotypeSite, HTMLStencilElement {
    }
    var HTMLBinotypeSiteElement: {
        prototype: HTMLBinotypeSiteElement;
        new (): HTMLBinotypeSiteElement;
    };
    interface HTMLSampleSiteElement extends Components.SampleSite, HTMLStencilElement {
    }
    var HTMLSampleSiteElement: {
        prototype: HTMLSampleSiteElement;
        new (): HTMLSampleSiteElement;
    };
    interface HTMLElementTagNameMap {
        "binotype-site": HTMLBinotypeSiteElement;
        "sample-site": HTMLSampleSiteElement;
    }
}
declare namespace LocalJSX {
    interface BinotypeSite {
        /**
          * @default false
         */
        "debug"?: boolean | "site" | "context";
        "site"?: binotype.Site | string;
    }
    interface SampleSite {
    }

    interface BinotypeSiteAttributes {
        "site": binotype.Site | string;
        "debug": string;
    }

    interface IntrinsicElements {
        "binotype-site": Omit<BinotypeSite, keyof BinotypeSiteAttributes> & { [K in keyof BinotypeSite & keyof BinotypeSiteAttributes]?: BinotypeSite[K] } & { [K in keyof BinotypeSite & keyof BinotypeSiteAttributes as `attr:${K}`]?: BinotypeSiteAttributes[K] } & { [K in keyof BinotypeSite & keyof BinotypeSiteAttributes as `prop:${K}`]?: BinotypeSite[K] };
        "sample-site": SampleSite;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "binotype-site": LocalJSX.IntrinsicElements["binotype-site"] & JSXBase.HTMLAttributes<HTMLBinotypeSiteElement>;
            "sample-site": LocalJSX.IntrinsicElements["sample-site"] & JSXBase.HTMLAttributes<HTMLSampleSiteElement>;
        }
    }
}
